# Generated by Django 4.1.1 on 2022-10-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phnum', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('PCM', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=150)),
                ('ProfilePicture', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
